name: nn-torch
channels:
  - pytorch
  - defaults
dependencies:
  - jupyterlab=1.2.6
  - matplotlib=3.1.3
  - numpy=1.18.1
  - python=3.7.6
  - pytorch=1.4.0
  - tensorboard=2.1.0
  - torchvision=0.5.0
